# Generated by Django 4.2.7 on 2025-03-30 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_add_faq_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqknowledgebase',
            options={'ordering': ['category', 'order', 'question'], 'verbose_name': 'FAQ Item', 'verbose_name_plural': 'FAQ Knowledge Base'},
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us Page'), ('contact', 'Contact Us Page'), ('footer', 'Footer'), ('header', 'Header'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Content',
                'verbose_name_plural': 'Website Content',
                'ordering': ['content_type', 'title'],
            },
        ),
    ]
