# Generated by Django 4.2.7 on 2025-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_add_performed_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketaction',
            name='action_taken',
            field=models.CharField(blank=True, help_text='Brief description of action taken', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Detailed summary of resolution', null=True),
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.TextField(blank=True, help_text='Comma-separated list of permissions', null=True),
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='action_type',
            field=models.CharField(choices=[('review', 'Reviewed ticket'), ('update', 'Updated ticket information'), ('escalate', 'Escalated to higher support'), ('assign', 'Assigned/reassigned ticket'), ('status_change', 'Changed ticket status'), ('note', 'Added internal note'), ('reset_password', 'Reset user password'), ('other', 'Other action')], default='note', max_length=20),
        ),
    ]
