apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tms-application
  namespace: argocd
  labels:
    app: tms
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/manirasu28/gitops-project.git
    targetRevision: HEAD
    path: infrastructure/helm-chart
    helm:
      valueFiles:
        - values.yaml
      releaseName: tms
  destination:
    server: https://kubernetes.default.svc
    namespace: tms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 